
name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install newsapi-python
    - name: Run script
      env:
        FIRSTAPI: ${{ secrets.FIRSTAPI }}
        SECONDAPI: ${{ secrets.SECONDAPI }}
        THIRDAPI: ${{ secrets.THIRDAPI }}
        FOURTHAPI: ${{ secrets.FOURTHAPI }}
        FIFTHAPI: ${{ secrets.FIFTHAPI }}
        SIXTHAPI: ${{ secrets.SIXTHAPI }}
        SEVENTHAPI: ${{ secrets.SEVENTHAPI }}
      run: |
        python main.py
        
        
    - name: Push directory to another repository target directory
      # You may pin to the exact commit or the version.
      # uses: darkquasar/github-action-push-to-another-repository@4aa3f38a18f50c45b3e7254f2731e6d5b4071d62
      uses: darkquasar/github-action-push-to-another-repository@v1.3
      with:
        # Source directory from the origin directory
        source-directory: gb/ in/ us/
        # Target directory on the target repository where files from the source directory of the current repo will be copied to
        target-directory: news-apu
        # Name of the destination username/organization
        destination-github-username: pranavpk404
        # Destination repository
        destination-repository-name: news-api-source
